USE active_test;
CREATE TABLE number (
  id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  myNumber INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO number (myNumber) VALUES (1), (5);
